
class ProblemCategory(object):
    DEF_KEYWORD = 0
    KEYWORD_DEF = 1
    KEYWORD_DEF_START_END = 2

    CHAR_KEYWORD = 3
    KEYWORD_CHAR = 4
    SITUATION_KEYWORD = 5
    KEYWORD_SITUATION = 6
    SITUATION_CHAR = 7
    CHAR_SITUATION = 8
    SITUATION_ACTION = 9
    ACTION_EFFECT = 10
    ACTION_REASON = 11
    KEYWORD_COMPARISON = 12
    SITUATION_DEF = 13
    OTHER = 666
